//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gate.CLanguage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GateCLang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #define _CRT_SECURE_NO_WARNINGS
        ///#define __USE_MINGW_ANSI_STDIO
        ///
        ///#include &lt;stdio.h&gt;  
        ///#include &lt;stdint.h&gt;  
        ///#include &lt;stdarg.h&gt;  
        ///#include &lt;string.h&gt;  
        ///
        ///#define EXPORT __declspec(dllexport)  
        ///
        ///typedef enum {
        ///   ARG_POINTER = 0,
        ///#[Types:]#
        ///   ARG_#[TypeName]#=#[TypeCode]#,
        ///#[;]#
        ///}ArgType;
        ///
        ///typedef struct 
        ///{
        ///   ArgType type;
        ///   void* value_p;
        ///}Arg_t;
        ///
        ///EXPORT int sscanf_wrapper(const char* buffer, const char* format, ...);
        ///EXPORT int sprintf_wrapper(char* outBuffer, size_t outBufferSize, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stdio_template {
            get {
                return ResourceManager.GetString("stdio_template", resourceCulture);
            }
        }
    }
}
