//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     LangBase Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gate.CLanguageTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GateCLangTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma pack(4)
        ///
        ///typedef struct S1
        ///{
        ///   char f1;
        ///   int f2 : 5;
        ///}S1;
        ///
        ///typedef struct S2
        ///{
        ///   char f1;
        ///   S1 f2;
        ///}S2;
        ///
        ///#pragma pack(1)
        ///typedef struct S3
        ///{
        ///   char f1;
        ///#pragma pack(4)
        ///   int f21;
        ///   char f4;
        ///}S3;
        ///
        ///#pragma pack(1)
        ///typedef struct S4
        ///{
        ///   char f1;
        ///   int f21;
        ///#pragma pack(4)
        ///   char f4;
        ///}S4;.
        /// </summary>
        internal static string bit_field_test_c {
            get {
                return ResourceManager.GetString("bit_field_test.c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&quot;struct __declspec(dllimport) S_t{ int a; int b : 2; struct {}; };&quot;,
        /////&quot;struct __declspec(dllimport) S_t{ int a; int b : 2; struct { int a; }; };&quot;,
        /////&quot;struct {};&quot;,
        /////&quot;struct __declspec(dllimport) S_t;&quot;,
        /////&quot;enum __declspec(dllimport) E_t;&quot;,
        /////&quot;enum __declspec(dllimport) E_t { lab = 0 , lab1 };&quot;,
        /////&quot;enum __declspec(dllimport) { lab = 0 , lab1 };&quot;,
        /////&quot;auto c = 5.0;&quot;,
        /////&quot;int a[];&quot;,
        /////&quot;int func ( int a , float );&quot;,
        /////&quot;typedef int (*PointerOfMatrix)[3][4];&quot;,
        /////&quot;typedef int* MatrixOfPointer[3][4];&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string interpret_dev_c {
            get {
                return ResourceManager.GetString("interpret_dev.c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct S1
        ///{
        ///   int f11;
        ///};
        ///
        ///
        ///void main()
        ///{
        ///   struct S2
        ///   {
        ///      int f21;
        ///      struct S1 f22;
        ///   };
        ///}.
        /// </summary>
        internal static string scope_test_c {
            get {
                return ResourceManager.GetString("scope_test.c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //f1 + f2
        ///struct BaseStruct
        ///{
        ///   typedef int inda;
        ///
        ///   int f1;
        ///
        ///   union
        ///   {
        ///      char bf1 : 2;
        ///      char bf2 : 2;
        ///   };
        ///};
        ///
        /// typedef struct TestStruct
        /// {
        ///    union
        ///    {
        ///       struct BaseStruct bs;
        ///
        ///       int i32;
        ///
        ///       struct
        ///       {
        ///          int b2f1 : 31;
        ///          int b2f2 : 4;
        ///          char  b2f3 : 5;
        ///       };
        ///    };
        /// };
        ///
        ///int g1,g2;
        ///
        /// void main(int p1 , int p2)
        /// {
        ///    int a, b;
        ///
        ///    {
        ///       float p1;
        ///    }
        ///
        /// }.
        /// </summary>
        internal static string struct_test_c {
            get {
                return ResourceManager.GetString("struct_test.c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///#include &lt;test1.h&gt;
        ///
        ////**/
        ///#pragma
        ///
        ///
        ///#define A B+C	
        ///#define B A
        ///#define C 66
        ///#define S1(s) #s s
        ///#define S(s) S1(s+B)
        ///#define V(a,...) a __VA_ARGS__
        ///#define S2(...) #__VA_ARGS__
        ///#define S3(...) X ## __VA_ARGS__
        ///
        /////EXP:?XA+66 ?
        ///? S3(A) ?
        /////EXP:?&quot;A&quot; ?
        ///? S2(A) ?
        /////EXP:?&quot;A+66+B&quot; A+66+B+66  ?
        ///? S(A) ?
        /////EXP:?A+66 B+66,66 ?
        ///? V(A, B, C) ?
        ///
        ///#define M1(a) micky a
        ///#define M(a,b) a x ## y b
        ///
        /////EXP:A+66
        ///A
        /////EXP:B+66
        ///B
        ///
        ///#ifdef A
        /////EXP:Yes
        ///Yes
        /////EXP:!A+66 xy B+66 !
        ///!M(A, B)!
        /////EXP:6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test1_c {
            get {
                return ResourceManager.GetString("test1.c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///#define PI 3.14
        ///
        /////EXP:TEST
        ///TEST
        ///
        ///.
        /// </summary>
        internal static string test1_h {
            get {
                return ResourceManager.GetString("test1.h", resourceCulture);
            }
        }
    }
}
