<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
     <Platforms>x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.58" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.2" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GateToolsView\GateToolsView.csproj" />
    <ProjectReference Include="..\GateTools\GateTools.csproj" />
     <ProjectReference Include="..\ScintillaNet\ScintillaNet.csproj" />
     <ProjectReference Include="..\SeaMath\SeaMath.csproj" />
  </ItemGroup>

   <PropertyGroup>
      <NoWarn>$(NoWarn);NU1701;NU1901;NU1902</NoWarn>
   </PropertyGroup>


</Project>