<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GateDock\GateDock.csproj" />
    <ProjectReference Include="..\GateLangBase\GateLangBase.csproj" />
    <ProjectReference Include="..\GateToolsView\GateToolsView.csproj" />
    <ProjectReference Include="..\GateTools\GateTools.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(ProjectDir)..\GatePad\$(OutputPath)\PlugIns\$(ProjectName)&quot;&#xD;&#xA;xcopy &quot;$(TargetDir)*.dll&quot; &quot;$(ProjectDir)..\GatePad\$(OutputPath)\PlugIns\$(ProjectName)&quot; /Y /I /D" />
  </Target>

   <PropertyGroup>
      <NoWarn>$(NoWarn);NU1701;NU1901;NU1902</NoWarn>
   </PropertyGroup>

</Project>